version: '3.3'
services:
    pagermon:
        build: ./server
        image: pagermon
        container_name: pagermon
        ports:
            - 3000:3000
        volumes:
            - ./data/pagermon:/data
        env_file:
            - ./default.env
    mysql:
        image: mysql:5.7
        volumes:
            - ./data/mysql:/var/lib/mysql
        env_file:
            - ./default.env
